site_name: Bl4ckSh33p
site_url: https://bl4cksh33p.github.io
theme:
  name: material
  logo: images/bl4cksh33p_logo.png
  favicon: images/bl4cksh33p_logo.png
  palette:
    primary: black
    accent: deep purple
nav:
  - Accueil: index.md
  - Writeups:
    - HackTheBox: test.md
    - RootMe:
      - Injection SQL - Contournement de filtres: writeups/root-me/sql-injection.md
    - TryHackMe: test.md
    - CTF: test.md
  - Cheatsheets:
    - NMAP: cheatsheets/nmap.md
  - Training:
    - Web Exploitation: test.md
  - À propos: about.md
