site_name: Bl4ckSh33p
site_url: https://bl4cksh33p.github.io
theme:
  name: material
  palette:
    primary: black
    accent: deep purple
nav:
  - Accueil: index.md
  - Writeups:
      - HackTheBox: writeups/htb.md
      - RootMe: writeups/rootme.md
      - TryHackMe: writeups/thm.md
      - CTF: writeups/ctf.md
  - Cheatsheets: cheatsheets/index.md
  - Training: training/index.md
  - À propos: about.md
