site_name: Bl4ckSh33p
site_url: https://bl4cksh33p.github.io
theme:
  name: material
  logo: images/bl4cksh33p_logo.png
  favicon: images/bl4cksh33p_logo.png
  palette:
    primary: black
    accent: deep purple
nav:
  - Accueil: index.md
  - Writeups:
    - HackTheBox: test.md
    - root-me:
      - api-broken-access: writeups/root-me/api-broken-access.md
      - api-mass-assignment: writeups/root-me/api-mass-assignment.md
      - bash-system1: writeups/root-me/bash-system1.md
      - chal-5: writeups/root-me/chal-5.md
      - CRLF: writeups/root-me/CRLF.md
      - directory-transversal: writeups/root-me/directory-transversal.md
      - ELF-x64-basic-heap-overflow: writeups/root-me/ELF-x64-basic-heap-overflow.md
      - ELF-x64-stack-buffer-overflow-basic-2: writeups/root-me/ELF-x64-stack-buffer-overflow-basic-2.md
      - file-upload-null-byte: writeups/root-me/file-upload-null-byte.md
      - file-upload-type-MIME: writeups/root-me/file-upload-type-MIME.md
      - flask-unsecure-session: writeups/root-me/flask-unsecure-session.md
      - HTTP-DNS-Rebinding: writeups/root-me/HTTP-DNS-Rebinding.md
      - hub challenge root-me: writeups/root-me/hub challenge root-me.md
      - Insecure-code-management: writeups/root-me/Insecure-code-management.md
      - install files: writeups/root-me/install files.md
      - JWT-Unsecure-File-Signature-1: writeups/root-me/JWT-Unsecure-File-Signature-1.md
      - JWT-Unsecure-File-Signature: writeups/root-me/JWT-Unsecure-File-Signature.md
      - Local-File-Inclusion-Double-encoding: writeups/root-me/Local-File-Inclusion-Double-encoding.md
      - Local-File-Inclusion: writeups/root-me/Local-File-Inclusion.md
      - multiples codages: writeups/root-me/multiples codages.md
      - Nginx-Alias-Misconfiguration: writeups/root-me/Nginx-Alias-Misconfiguration.md
      - Nginx-root-location-misconfiguration: writeups/root-me/Nginx-root-location-misconfiguration.md
      - NoSQL-injection-Authentification: writeups/root-me/NoSQL-injection-Authentification.md
      - OSPF-Authentification: writeups/root-me/OSPF-Authentification.md
      - PE32-Stack-buffer-overflow-basic: writeups/root-me/PE32-Stack-buffer-overflow-basic.md
      - PHP-assert: writeups/root-me/PHP-assert.md
      - programmation: writeups/root-me/programmation.md
      - PyRat-Enchères: writeups/root-me/PyRat-Enchères.md
      - Remote-File-Inclusion: writeups/root-me/Remote-File-Inclusion.md
      - root-me: writeups/root-me/root-me.md
      - Rootme-appscript-12-input: writeups/root-me/Rootme-appscript-12-input.md
      - Rootme-cryptanalyse-5-Hash-LM: writeups/root-me/Rootme-cryptanalyse-5-Hash-LM.md
      - rootmechallenge - CSRF - 0 protection: writeups/root-me/rootmechallenge - CSRF - 0 protection.md
      - rootmechallenge - CSRF - contournement de jeton: writeups/root-me/rootmechallenge - CSRF - contournement de jeton.md
      - SQL-injection-Authentification-2: writeups/root-me/SQL-injection-Authentification-2.md
      - SQL-injection-Authentification-GBK: writeups/root-me/SQL-injection-Authentification-GBK.md
      - SQL-injection-Authentification: writeups/root-me/SQL-injection-Authentification.md
      - sql-injection-contournement-de-filtres: writeups/root-me/sql-injection-contournement-de-filtres.md
      - SQL-injection-Numérique: writeups/root-me/SQL-injection-Numérique.md
      - SQL-injection-String: writeups/root-me/SQL-injection-String.md
      - Trafic Global System for Mobile communications: writeups/root-me/Trafic Global System for Mobile communications.md
      - XMPP - Authentification: writeups/root-me/XMPP - Authentification.md
      - XSS - Dom Based: writeups/root-me/XSS - Dom Based.md
      - XSS - Server Side: writeups/root-me/XSS - Server Side.md
      - Injection SQL - Contournement de filtres: writeups/root-me/sql-injection.md
    - TryHackMe: test.md
    - CTF: test.md
  - Cheatsheets:
    - NMAP: cheatsheets/nmap.md
  - Training:
    - Web Exploitation: test.md
  - À propos: about.md
