site_name: Bl4ckSh33p
site_url: https://bl4cksh33p.github.io
theme:
  name: material
  logo: images/bl4cksh33p_logo.png
  favicon: images/bl4cksh33p_logo.png
  palette:
    primary: black
    accent: deep purple
nav:
  - Accueil: index.md
  - Writeups:
      - HackTheBox:
      - RootMe:
          - Injection SQL - Contournement de filtres: writeups/root-me/sql-injection.md
      - TryHackMe:
      - CTF:
  - Cheatsheets:
      - NMAP: cheatsheets/nmap.md
  - Training:
      - Web Exploitation:
  - À propos: about.md
